[package]
name = "egui_enc"
version = "0.1.2"
edition = "2021"
authors = ["L420Y"]
description = "Simple egui rust file encryptor. Enjoy!"

[dependencies]
eframe = "0.22.0"
rfd = "0.11"
ascii_converter = "0.3.0"
