[package]
name = "egui_enc"
version = "0.1.3"
edition = "2021"
authors = ["L420Y"]
description = "Simple egui rust file encryptor. Enjoy!"
repository = "https://github.com/l420y/egui_encryptor"

[dependencies]
eframe = "0.24.1"
rfd = "0.12.1"
ascii_converter = "0.3.0"
base64 = "0.21.5"
