[package]
name = "egui_enc"
version = "0.1.1"
edition = "2021"
authors = ["L420Y"]
description = "Simple egui rust file encryptor. Enjoy!"

[dependencies]
eframe = "0.22.0"
rfd = "0.11"
math_matrix = "1.1.0"
